Added favicon
PantherHackers/rails_site pull request #23
Opened 2017-03-20 00:22 UTC by Litagano-M

Closes #12

2017-03-24 00:19 UTC, ferrerluis requested changes
Some very small details. Good job so far! @Litagano-M

2017-03-24 00:19 UTC, ferrerluis commented on app/views/layouts/application.html.erb
> +    <%= favicon_link_tag       'favicon.ico' %>
I saw this file. Could you please talk to Harsha and get Pbot only without the blue square background and without the shadow? Then replace the `favicon.ico` file with that one

2017-03-24 00:19 UTC, ferrerluis commented on .gitignore
> +# Ignore IDE config files
Submit this in a separate commit pls

2017-03-27 20:52 UTC, Litagano-M commented on .gitignore
> +# Ignore IDE config files
Will do!

2017-04-07 05:17 UTC, Litagano-M commented
Changed.

2017-04-08 06:01 UTC, closed without merging