Event Model Rework
PantherHackers/rails_site pull request #9
Opened 2017-03-05 06:02 UTC by bcabio

2017-03-09 00:22 UTC, bcabio commented
Model to pull events from PantherHackers' public calendar. 

Pull_calendar_data returns array of Events

2017-03-09 03:31 UTC, bcabio commented
Modified Application.html.erb to have favicon.ico import
Added favicon.ico to /public/

2017-03-09 04:12 UTC, ferrerluis commented
@bcabio Can you reset the favicon.ico commit and make a different PR for that? Just to keep things tidy. Thank you tho!

2017-03-09 05:11 UTC, ferrerluis requested changes
Good job! Let's get these changes ready so we can continue by adding migrations (fancy way of saying: create a table in the database) and creating a rake task that pretty much does `pull_calendar_data`

2017-03-09 05:11 UTC, ferrerluis commented on app/models/event.rb
> +	  @start_datetime = event_json['start']
I think the name `start` should be enough. It should be clear the event has a start and an end.

Also, the value stored in there is actually a hash that looks like `{"dateTime"=>"2017-02-08T19:00:00-05:00", "timeZone"=>"America/New_York"}`. This is redundant since `dateTime` already holds the timezone value.

Lastly, after you change it to store the specific `dateTime` within the hash, also turn it into a `DateTime` object. You can do this by passing the string into `DateTime.iso8601(date_string)`.

2017-03-09 05:11 UTC, ferrerluis commented on app/models/event.rb
> +	  @end_datetime = event_json['end']
Same as above

2017-03-09 05:11 UTC, ferrerluis commented on app/models/event.rb
> +	  @link = (event_json['description'].to_s).split.first
You don't need the parentheses. Also, I am not sure why you would need the `#to_s`, since `event_json['description']` is already a string.

2017-03-09 05:11 UTC, ferrerluis commented on app/models/event.rb
> +	def initialize(event_json)
Receiving `event_json` is not very good in my book. I would prefer it to simply get the parameters in order and let `pull_calendar_data` manage the creation.

So `Event.new(event_json['summary'], event_json['start'], ...)`. This makes the class and constructor simpler and leaves more work for the other methods/classes implementing it.

If you feel that passing in a hash makes it easier and is vastly used, you can always create another static method `self.from_hash` that creates a new `Event` based on the hash (kinda how you're currently doing)

2017-03-09 05:11 UTC, ferrerluis commented on app/models/event.rb
> +	  uri = URI('https://www.googleapis.com/calendar/v3/calendars/calendarId/events')
You don't seem to be using the Google API wrapper anymore. Any reasons? Wrapper gems usually keep code cleaner. The code right now is pretty cluttered for a simple HTTP GET request

2017-03-09 05:11 UTC, ferrerluis commented on app/models/event.rb
> +	  	puts event
`puts` are great for development, but pretty useless for production. Remember to delete them before pushing

2017-03-09 05:11 UTC, ferrerluis commented on app/models/event.rb
> +	  response['items'].each do |event|
Beware of `Array#map`. It lets you do what you're doing here without creating an intermediate array to push the events to. It iterates though the array, executes whatever you want, and returns the results in a new array. Look it up! 🙂

2017-03-09 05:11 UTC, ferrerluis commented on app/models/event.rb
> +	  event_array
If you use `Array#map` you won't need this

2017-03-20 05:02 UTC, bcabio commented on app/models/event.rb
> +	  uri = URI('https://www.googleapis.com/calendar/v3/calendars/calendarId/events')
The Google API wrapper requires OAuth as far as I know which is why I'm just doing a GET request with the API key in the `.env` file.

2017-03-20 16:30 UTC, bcabio commented on app/models/event.rb
> +	  @link = (event_json['description'].to_s).split.first
I have `#to_s` because, when I don't have it, it gives me a `NoMethodError: undefined method 'split' for nil:Nilclass` error.

2017-03-24 00:27 UTC, ferrerluis requested changes
Back your way. Only added some small comments. After this, let's turn this into a simple, actual Rails model that is saved in the database, and let's create a rake task that populates the database

2017-03-24 00:27 UTC, ferrerluis commented on .env.example
> -PH_MYSQL_PASSWORD=db_pass_aws
Why were all these lines deleted?

2017-03-24 00:27 UTC, ferrerluis commented on app/models/event.rb
> +    event_array
You're not ever dealing with `event_array`. You just use it for returning the variable at this point. Instead, stop assigning the value in line 26 and just return that value right away.

Not sure how to explain this, so if that didn't make sense, LMK in Slack and I'll explain.

Like, make `response['items'].map { |event|  ...` your last statement

2017-03-24 00:27 UTC, ferrerluis commented on app/models/event.rb
> +    event_array = response['items'].map { |event|
You are using the `.map { ... }` syntax. For multiline stuff, use `.map do |event|` and close the block with `end` on a different line.

e.g.
```ruby
response['items'].map do |event|
...
...
...
end
```

2017-03-24 00:27 UTC, ferrerluis commented on app/models/event.rb
> +  def self.pull_calendar_data
Let's go ahead and change this function name for `self.all`, since it is returning all Event objects. Calling `Event.all` reads better.

2017-08-03 16:20 UTC, merged